# Generated by Django 5.2 on 2025-04-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bosque_trees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PODA', 'Poda'), ('DOENCA', 'Doença Identificada'), ('TRATAMENTO', 'Tratamento Aplicado'), ('ADUBACAO', 'Adubação'), ('MONITORAMENTO', 'Monitoramento Geral'), ('FLORACAO', 'Floração'), ('FRUTIFICACAO', 'Frutificação')], help_text='Tipo de evento ocorrido.', max_length=50)),
                ('event_date', models.DateTimeField(blank=True, help_text='Data e hora em que o evento ocorreu ou foi registrado.', null=True)),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do evento.', null=True)),
                ('tree', models.ForeignKey(help_text='A árvore à qual este evento está associado.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bosque_trees.tree')),
            ],
            options={
                'verbose_name': 'Evento da Árvore',
                'verbose_name_plural': 'Eventos das Árvores',
                'ordering': ['-event_date', '-id'],
            },
        ),
    ]
