# Generated by Django 5.2 on 2025-04-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosque_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treeevent',
            options={'ordering': ['-event_date', 'id'], 'verbose_name': 'Evento da Árvore', 'verbose_name_plural': 'Eventos das Árvores'},
        ),
    ]
