# Generated by Django 5.2 on 2025-05-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosque_trees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='code',
            new_name='accession',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='species',
            new_name='calcfullname',
        ),
        migrations.AddField(
            model_name='tree',
            name='familyname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='vernacularname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
